### ISSUE TITLE
`Input.File` instances are equal even if contents differ

### ISSUE THREAD

**Issue by stephenjudkins** [olafurpg/metaconfig#67]
To reproduce:
* create a file `p`
* construct an `Input.File` `a` with given path `p`
* change file at `p`
* construct an `Input.File` `b` with given path `p`
* compare `a` and `b` using `==`, `hashCode`, `equals`, etc...

Expected: these inputs not be equal
Actual: these inputs are said to be equal

**Comment by olafurpg** [comment]
Metaconfig `Input` is not used in scalafix, Scalafix uses `scala.meta.inputs.Input` instead.

**Comment by olafurpg** [comment]
BTW, since https://github.com/scalameta/scalameta/issues/1068 got fix this may no longer be a problem with `scala.meta.inputs.Input`
