### ISSUE TITLE
Publish for 2.13.0

### ISSUE THREAD

**Issue by gabro** [olafurpg/metaconfig#71]
Currently blocked by paiges (https://github.com/typelevel/paiges/issues/152)

**Comment by poslegm** [comment]
@gabro please take look at https://github.com/typelevel/paiges/pull/160. I tried to update paiges, but there is some problems. Maybe you know how to solve it :sweat_smile:

**Comment by SethTisue** [comment]
paiges [published](https://github.com/typelevel/paiges/issues/152#issuecomment-517752596)
